### ISSUE TITLE
开放提交按钮的个性化配置

### ISSUE THREAD

**Issue by itper** [jincdream/sorm#5]
![image](https://user-images.githubusercontent.com/4143986/73709620-84cf2800-473c-11ea-8086-4ac428dc8af9.png)

**Comment by jincdream** [comment]
需要配置些什么？
样式么？

**Comment by jincdream** [comment]
```vue
<schema-renderer schema="{{schema}}">
    <btn slot="footer" slot-scope="footer" api="{{footer}}"/>
</schema-renderer>
```
**<schema-renderer schema="{{schema}}" onSubmit="formSubmit">** 中，如果onSubmit填了的话，将会用默认的提交按钮，没有的话需要自定义slot，slot name 为footer， footer里面有**getValues**、**reset**、**submit**三个方法
